apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blue-green-automatic-metrics

resources:
  - namespace.yaml
  - rollout.yaml
  - rollout-bluegreen-active.yaml
  - rollout-bluegreen-preview.yaml
  - random-fail.yaml
