apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout
  namespace: argocd
spec:
  project: rollout
  source:
    repoURL: "https://github.com/TamerlanG/argocd-demo"
    path: base
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: rollouts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
