apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: rollout
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: This is the project that my rollout applications will be in.
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
