apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-automatic-preview
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30084
      protocol: TCP
  selector:
    app: rollout-bluegreen-automatic
