apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-bluegreen-automatic
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-bluegreen-automatic
  template:
    metadata:
      labels:
        app: rollout-bluegreen-automatic
    spec:
      containers:
        - name: rollouts-demo
          image: argoproj/rollouts-demo:red
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
  strategy:
    blueGreen:
      activeService: rollout-bluegreen-automatic-active
      previewService: rollout-bluegreen-automatic-preview
      prePromotionAnalysis:
        templates:
        - templateName: random-fail
