apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      owner: tamerlan

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
