apiVersion: v1
kind: Service
metadata:
  name: rick-roll-preview
  labels:
    app: rick-roll
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: rick-roll-preview
  type: ClusterIP
