apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-mario
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: mario
  template:
    metadata:
      labels:
        app: mario
    spec:
      containers:
        - name: rollouts-demo
          image: argoproj/rollouts-demo:red
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
  strategy:
    blueGreen:
      activeService: mario-service
      previewService: mario-preview-service
      prePromotionAnalysis:
        templates:
          - templateName: e2e-tests
        args:
          - name: service-name
            value: mario-service
          - name: stable-hash
            valueFrom:
              podTemplateHashValue: Stable
          - name: latest-hash
            valueFrom:
              podTemplateHashValue: Latest
