apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: argocd-demo
  labels:
    app: nginx
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx 